/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import control.PustakaControl;
import exception.jenisException;
import exception.idException;
import model.Pustaka;
/**
    Kelas    : PBO A
 * Anggota :
 * 1. Vigo Made Prastyo      (210711303)
 * 2. Gede Koosei Wibawa   (210711308
 */
public class PustakaView extends javax.swing.JFrame {

    private PustakaControl pc;
    String action = null;
    
    public PustakaView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        pc = new PustakaControl();
        showPustaka();
    }

    public void setComponent(boolean value){
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
        
        idInput.setEnabled(value);
        judulInput.setEnabled(value);
        tahunInput.setEnabled(value);
        penerbitInput.setEnabled(value);
        
        radioBuku.setEnabled(value);
        radioMajalah.setEnabled(value);
        
        edisiInput.setEnabled(false);
        volumeInput.setEnabled(false);
         
    }
    
    public void clearText(){
        idInput.setText("");
        judulInput.setText("");
        tahunInput.setText("");
        penerbitInput.setText("");
        searchInput.setText("");
        edisiInput.setText("");
        volumeInput.setText("");
    }
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    private void showPustaka(){
        txtABuku.setText(pc.showDataBuku());
        txtAMajalah.setText(pc.showDataMajalah());
    }
    
    private void idException() throws idException{
        if(idInput.getText().length()<5 || idInput.getText().length() > 8){
            throw new idException();
        }
        
    }
    
    private void jenisException() throws jenisException{
        if(radioBuku.isSelected() == false && radioMajalah.isSelected()==false){
            throw new jenisException();
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidePanel = new javax.swing.JPanel();
        npmPanel = new javax.swing.JPanel();
        npmVigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kelompokLabel = new javax.swing.JLabel();
        npmPanel1 = new javax.swing.JPanel();
        priaTampan = new javax.swing.JLabel();
        npmPanel4 = new javax.swing.JPanel();
        npmKoosei = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        containerInputId = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputJudul = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        judulInput = new javax.swing.JTextField();
        containerInputTahun = new javax.swing.JPanel();
        tahunLabel = new javax.swing.JLabel();
        tahunInput = new javax.swing.JTextField();
        containerInputPenerbit = new javax.swing.JPanel();
        penerbitLabel = new javax.swing.JLabel();
        penerbitInput = new javax.swing.JTextField();
        showDataPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtABuku = new javax.swing.JTextArea();
        showDataPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMajalah = new javax.swing.JTextArea();
        bukuLabel = new javax.swing.JLabel();
        majalahLabel = new javax.swing.JLabel();
        panelBuku = new javax.swing.JPanel();
        edisiLabel = new javax.swing.JLabel();
        edisiInput = new javax.swing.JTextField();
        radioBuku = new javax.swing.JRadioButton();
        panelMajalah = new javax.swing.JPanel();
        volumeLabel = new javax.swing.JLabel();
        volumeInput = new javax.swing.JTextField();
        radioMajalah = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(20, 108, 148));
        sidePanel.setForeground(new java.awt.Color(255, 255, 51));

        npmPanel.setBackground(new java.awt.Color(25, 167, 206));
        npmPanel.setForeground(new java.awt.Color(255, 255, 0));

        npmVigo.setBackground(new java.awt.Color(255, 255, 255));
        npmVigo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        npmVigo.setForeground(new java.awt.Color(246, 241, 241));
        npmVigo.setText("210711303");
        npmVigo.setAutoscrolls(true);

        javax.swing.GroupLayout npmPanelLayout = new javax.swing.GroupLayout(npmPanel);
        npmPanel.setLayout(npmPanelLayout);
        npmPanelLayout.setHorizontalGroup(
            npmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npmPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(npmVigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        npmPanelLayout.setVerticalGroup(
            npmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(npmVigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(25, 167, 206));

        kelompokLabel.setBackground(new java.awt.Color(246, 241, 241));
        kelompokLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        kelompokLabel.setForeground(new java.awt.Color(255, 255, 255));
        kelompokLabel.setText("KELOMPOK 7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kelompokLabel)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(kelompokLabel)
                .addContainerGap())
        );

        npmPanel1.setBackground(new java.awt.Color(25, 167, 206));
        npmPanel1.setForeground(new java.awt.Color(255, 255, 0));

        priaTampan.setBackground(new java.awt.Color(246, 241, 241));
        priaTampan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        priaTampan.setForeground(new java.awt.Color(246, 241, 241));
        priaTampan.setText("#priatampan");

        javax.swing.GroupLayout npmPanel1Layout = new javax.swing.GroupLayout(npmPanel1);
        npmPanel1.setLayout(npmPanel1Layout);
        npmPanel1Layout.setHorizontalGroup(
            npmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npmPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(priaTampan)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        npmPanel1Layout.setVerticalGroup(
            npmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npmPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priaTampan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        npmPanel4.setBackground(new java.awt.Color(25, 167, 206));
        npmPanel4.setForeground(new java.awt.Color(255, 255, 0));

        npmKoosei.setBackground(new java.awt.Color(246, 241, 241));
        npmKoosei.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        npmKoosei.setForeground(new java.awt.Color(246, 241, 241));
        npmKoosei.setText("210711308");

        javax.swing.GroupLayout npmPanel4Layout = new javax.swing.GroupLayout(npmPanel4);
        npmPanel4.setLayout(npmPanel4Layout);
        npmPanel4Layout.setHorizontalGroup(
            npmPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npmPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(npmKoosei)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        npmPanel4Layout.setVerticalGroup(
            npmPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, npmPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(npmKoosei)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(npmPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(npmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(npmPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(npmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(npmPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(npmPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(25, 167, 206));

        titleContent.setBackground(new java.awt.Color(187, 187, 187));
        titleContent.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleContent.setForeground(new java.awt.Color(254, 247, 255));
        titleContent.setText("OBJECT PERSISTENCE 1");

        addBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        containerInputId.setBackground(new java.awt.Color(246, 241, 241));

        idLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idLabel.setText("Id Pustaka");

        javax.swing.GroupLayout containerInputIdLayout = new javax.swing.GroupLayout(containerInputId);
        containerInputId.setLayout(containerInputIdLayout);
        containerInputIdLayout.setHorizontalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        containerInputIdLayout.setVerticalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        containerInputJudul.setBackground(new java.awt.Color(246, 241, 241));

        judulLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        judulLabel.setText("Judul Pustaka");

        javax.swing.GroupLayout containerInputJudulLayout = new javax.swing.GroupLayout(containerInputJudul);
        containerInputJudul.setLayout(containerInputJudulLayout);
        containerInputJudulLayout.setHorizontalGroup(
            containerInputJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerInputJudulLayout.createSequentialGroup()
                .addComponent(judulInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        containerInputJudulLayout.setVerticalGroup(
            containerInputJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputJudulLayout.createSequentialGroup()
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        containerInputTahun.setBackground(new java.awt.Color(246, 241, 241));

        tahunLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tahunLabel.setText("Tahun Terbit");

        javax.swing.GroupLayout containerInputTahunLayout = new javax.swing.GroupLayout(containerInputTahun);
        containerInputTahun.setLayout(containerInputTahunLayout);
        containerInputTahunLayout.setHorizontalGroup(
            containerInputTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tahunLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerInputTahunLayout.createSequentialGroup()
                .addComponent(tahunInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        containerInputTahunLayout.setVerticalGroup(
            containerInputTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputTahunLayout.createSequentialGroup()
                .addComponent(tahunLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        containerInputPenerbit.setBackground(new java.awt.Color(246, 241, 241));

        penerbitLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        penerbitLabel.setText("Penerbit");

        javax.swing.GroupLayout containerInputPenerbitLayout = new javax.swing.GroupLayout(containerInputPenerbit);
        containerInputPenerbit.setLayout(containerInputPenerbitLayout);
        containerInputPenerbitLayout.setHorizontalGroup(
            containerInputPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputPenerbitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penerbitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerInputPenerbitLayout.createSequentialGroup()
                .addComponent(penerbitInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerInputPenerbitLayout.setVerticalGroup(
            containerInputPenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputPenerbitLayout.createSequentialGroup()
                .addComponent(penerbitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penerbitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        txtABuku.setColumns(20);
        txtABuku.setRows(5);
        jScrollPane1.setViewportView(txtABuku);

        javax.swing.GroupLayout showDataPanelLayout = new javax.swing.GroupLayout(showDataPanel);
        showDataPanel.setLayout(showDataPanelLayout);
        showDataPanelLayout.setHorizontalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        showDataPanelLayout.setVerticalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        txtAMajalah.setColumns(20);
        txtAMajalah.setRows(5);
        jScrollPane2.setViewportView(txtAMajalah);

        javax.swing.GroupLayout showDataPanel2Layout = new javax.swing.GroupLayout(showDataPanel2);
        showDataPanel2.setLayout(showDataPanel2Layout);
        showDataPanel2Layout.setHorizontalGroup(
            showDataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        showDataPanel2Layout.setVerticalGroup(
            showDataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        bukuLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bukuLabel.setText("Buku");

        majalahLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        majalahLabel.setText("Majalah");

        panelBuku.setBackground(new java.awt.Color(246, 241, 241));

        edisiLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        edisiLabel.setText("Edisi");

        buttonGroup1.add(radioBuku);
        radioBuku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioBuku.setText("Buku");
        radioBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioBukuMouseClicked(evt);
            }
        });
        radioBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBukuLayout = new javax.swing.GroupLayout(panelBuku);
        panelBuku.setLayout(panelBukuLayout);
        panelBukuLayout.setHorizontalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edisiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelBukuLayout.setVerticalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addComponent(radioBuku)
                .addGap(14, 14, 14)
                .addComponent(edisiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edisiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelMajalah.setBackground(new java.awt.Color(246, 241, 241));

        volumeLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        volumeLabel.setText("Volume");

        buttonGroup1.add(radioMajalah);
        radioMajalah.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioMajalah.setText("Majalah");
        radioMajalah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioMajalahMouseClicked(evt);
            }
        });
        radioMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMajalahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMajalahLayout = new javax.swing.GroupLayout(panelMajalah);
        panelMajalah.setLayout(panelMajalahLayout);
        panelMajalahLayout.setHorizontalGroup(
            panelMajalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMajalahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMajalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeLabel)
                    .addComponent(volumeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        panelMajalahLayout.setVerticalGroup(
            panelMajalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMajalahLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(radioMajalah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(editBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addGap(92, 92, 92)
                .addComponent(searchInput)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addGap(33, 33, 33))
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(titleContent)
                .addGap(27, 27, 27))
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containerInputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerInputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containerInputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bukuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showDataPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(majalahLabel)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addGap(31, 31, 31)
                                .addComponent(cancelBtn))
                            .addComponent(panelMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titleContent)
                .addGap(46, 46, 46)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containerInputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containerInputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveBtn)
                        .addComponent(cancelBtn))
                    .addComponent(containerInputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bukuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(majalahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showDataPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane3.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
       setComponent(true);
       clearText();
       searchInput.setText("");
       action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        idInput.setEnabled(false);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
       int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
       if(getAnswer == JOptionPane.YES_OPTION){
           try{
              pc.deleteDataKendaraan(searchInput.getText());
              clearText();
              showPustaka();
              JOptionPane.showConfirmDialog(null,"Data berhasil dihapus!");
         }catch (Exception e){
               System.out.println("Error : "+e.getMessage());
         }
       }else{
           JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus");
       }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            idException();
            jenisException();
            
            int edisi = 0;
            int volume =0;
            
            Pustaka pus = null;
            
            if(radioBuku.isSelected()==true){
                String jenis = "Buku";
                pus = new Pustaka(idInput.getText(),
                judulInput.getText(),
                jenis,
                tahunInput.getText(),
                penerbitInput.getText(),
                Integer.parseInt(edisiInput.getText()),
                volume);
            }else if(radioMajalah.isSelected()==true){
                String jenis = "Majalah";
                pus = new Pustaka(idInput.getText(),
                judulInput.getText(),
                jenis,
                tahunInput.getText(),
                penerbitInput.getText(),
                edisi,
                Integer.parseInt(volumeInput.getText()));
            }
            
            if(action.equals("Tambah")){
                pc.insertDataPustaka(pus);
            }else{
                pc.updateDataPustaka(pus, idInput.getText());
                JOptionPane.showConfirmDialog(null, "Data Berhasil diubah");
            }
            
            clearText();
            setComponent(false);
            setEditDeleteBtn(false);
            showPustaka();
        }catch(idException e){
            JOptionPane.showConfirmDialog(this, e.message());
        }catch(jenisException e2){
           JOptionPane.showMessageDialog(this, e2.message());
        }catch(NumberFormatException e3){
             JOptionPane.showMessageDialog(this, e3.getMessage());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        
        try{
            Pustaka pus = pc.searchDataPustaka(searchInput.getText());
            if(pus == null){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                idInput.setText(pus.getId_pustaka());
                judulInput.setText(pus.getJudul());
                tahunInput.setText(pus.getTahunTerbit());
                penerbitInput.setText(pus.getPenerbit());
                if(pus.getJenis().equalsIgnoreCase("Buku")){
                    radioBuku.setSelected(true);
                    edisiInput.setText(Integer.toString(pus.getEdisi()));
                }else{
                    radioMajalah.setSelected(true);
                    volumeInput.setText(Integer.toString(pus.getVolume()));
                }
            }
            
        }catch(Exception e) {
            System.out.println("Error : "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void radioBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBukuMouseClicked
        
    }//GEN-LAST:event_radioBukuMouseClicked

    private void radioMajalahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioMajalahMouseClicked
      
    }//GEN-LAST:event_radioMajalahMouseClicked

    private void radioBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBukuActionPerformed
        edisiInput.setEnabled(true);
        edisiInput.setText("");
        volumeInput.setEnabled(false);
        volumeInput.setText("");
    }//GEN-LAST:event_radioBukuActionPerformed

    private void radioMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMajalahActionPerformed
          volumeInput.setEnabled(true);
        edisiInput.setText("");
        edisiInput.setEnabled(false);
        volumeInput.setText("");
    }//GEN-LAST:event_radioMajalahActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PustakaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PustakaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PustakaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PustakaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PustakaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel bukuLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerInputId;
    private javax.swing.JPanel containerInputJudul;
    private javax.swing.JPanel containerInputPenerbit;
    private javax.swing.JPanel containerInputTahun;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField edisiInput;
    private javax.swing.JLabel edisiLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField judulInput;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel kelompokLabel;
    private javax.swing.JLabel majalahLabel;
    private javax.swing.JLabel npmKoosei;
    private javax.swing.JPanel npmPanel;
    private javax.swing.JPanel npmPanel1;
    private javax.swing.JPanel npmPanel2;
    private javax.swing.JPanel npmPanel3;
    private javax.swing.JPanel npmPanel4;
    private javax.swing.JLabel npmVigo;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPanel panelMajalah;
    private javax.swing.JTextField penerbitInput;
    private javax.swing.JLabel penerbitLabel;
    private javax.swing.JLabel priaTampan;
    private javax.swing.JLabel priaTampan1;
    private javax.swing.JLabel priaTampan2;
    private javax.swing.JRadioButton radioBuku;
    private javax.swing.JRadioButton radioMajalah;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel showDataPanel;
    private javax.swing.JPanel showDataPanel2;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField tahunInput;
    private javax.swing.JLabel tahunLabel;
    private javax.swing.JLabel titleContent;
    private javax.swing.JTextArea txtABuku;
    private javax.swing.JTextArea txtAMajalah;
    private javax.swing.JTextField volumeInput;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
